In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [7]:
arr[0:5] = 100 # Changes the original array

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_array = arr[0:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [13]:
slice_of_array[:] = 99 # Affects the original array!!!
slice_of_array

array([99, 99, 99, 99, 99])

In [14]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [15]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [16]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [17]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [19]:
arr_2d = np.array([[5, 10, 15],[20, 25, 30], [25, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [25, 40, 45]])

In [24]:
arr_2d.shape

(3, 3)

In [25]:
arr_2d[2]

array([25, 40, 45])

In [27]:
arr_2d[2, 1]

40

In [28]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [33]:
arr_2d[1]

array([20, 25, 30])

In [34]:
arr_2d[1:]

array([[20, 25, 30],
       [25, 40, 45]])

In [35]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [43]:
arr = np.arange(20, 31)
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [44]:
bool_arr = arr > 25
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [45]:
arr[bool_arr] # Use the boolean array as a filter to the original array
# Returns index values where the values are true

array([26, 27, 28, 29, 30])

In [46]:
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [53]:
arr[(arr > 25) & (arr < 29)] # Use a single ampersand; conditional selection filter

array([26, 27, 28])