In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
nested_list = [[1,2],[3,4],[5,6]]

In [5]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [9]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.linspace(0, 10, 6, dtype=int) # Includes the stopping value

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.linspace(0, 10, 21) # Includes the stopping value

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(2) # Array with 2 random numbers

array([0.52174664, 0.64946441])

In [14]:
np.random.rand(3, 4) # Uniform distribution

array([[0.71092902, 0.84072009, 0.87546806, 0.53823893],
       [0.59022253, 0.93100265, 0.7522769 , 0.86270299],
       [0.58214099, 0.67054519, 0.38702895, 0.16345847]])

In [15]:
np.random.randn(3) # Standard normal distribution

array([-0.5427939 , -0.42236342,  0.73979266])

In [16]:
np.random.randint(0, 10)

6

In [17]:
np.random.randint(0, 90, 10)

array([13, 14, 17, 83, 68, 45, 43, 26, 10, 52])

In [18]:
np.random.randint(0, 90, (2,3))

array([[49, 20,  9],
       [21,  0, 83]])

In [19]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [20]:
arr = np.arange(25)

In [21]:
randarray = np.random.randint(0, 50, 10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
randarray

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [24]:
arr.shape

(25,)

In [25]:
arr.reshape(5,5) # Original array is UNaffected

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
randarray.max()

39

In [27]:
randarray.min()

2

In [28]:
randarray.argmax()

7

In [29]:
randarray.argmin()

9

In [30]:
randarray.shape

(10,)

In [31]:
randarray.dtype # dtype = data type

dtype('int64')

In [32]:
myarr = np.random.rand(4)

In [33]:
myarr.dtype

dtype('float64')

In [34]:
myarr

array([0.02058449, 0.96990985, 0.83244264, 0.21233911])